apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: sangwoo-otel-poc
  namespace: sangwoo-otel-poc
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      hostmetrics:
        scrapers:
          cpu:
          disk:
          filesystem:
          load:
          memory:
          network:
          process:
          processes:
          paging:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    extensions:
      health_check:

    exporters:
      otlp:
        endpoint: tempo-us-central1.grafana.net:443
        headers:
          authorization: Basic <base64 encoded "userId:apiKey" string>
    service:
      extensions:
        - health_check
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp]

