import React from "react";
import { useState } from "react";
import styled from "styled-components";
import { Image, ImageContainer, ImageDescription } from "./Image";
import FaroErrors from "../assets/Faro-Errors.png";
import LokiErrorLog from "../assets/Loki-Error-Log.png";

const Container = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  background-color: #161b22;
  padding: 1rem;
  border-radius: 8px;
  font-family: "Roboto", sans-serif;
`;

const ErrorButton = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  background-color: #ff0000;
  color: black;
  border-radius: 8px;
  padding: 1rem;
  font-family: "Roboto", sans-serif;
  margin-bottom: 1rem;
  &:hover {
    cursor: pointer;
  }
`;

const Message = styled.div`
  font-size: 1.5rem;
  font-weight: bold;
  color: #5b5b5b;
  font-family: "Roboto", sans-serif;
`;

const ErrorMessageInput = styled.input`
  border-radius: 8px;
  padding: 1rem;
  margin-bottom: 1rem;
`;

const ErrorPage = (): JSX.Element => {
  const [isErrorThrown, setIsErrorThrown] = useState<Boolean>(false);
  const [errorMessage, setErrorMessage] = useState<string>("");
  const throwError = () => {
    setIsErrorThrown(true);
    throw new Error(errorMessage);
  };
  return (
    <>
      <Container>
        <ErrorMessageInput
          placeholder="Error message"
          onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
            setErrorMessage(e.target.value)
          }
        />
        <ErrorButton onClick={throwError}>
          Click me to throw an error
        </ErrorButton>
        {isErrorThrown && (
          <Message>Error has been thrown. Check console.</Message>
        )}
      </Container>
      <ImageContainer>
        <ImageDescription>
          You can see generated error on Faro Errors tab.
        </ImageDescription>
        <Image src={FaroErrors} />
        <ImageDescription>
          You can view logs generated by error on Loki.
        </ImageDescription>
        <Image src={LokiErrorLog} />
      </ImageContainer>
    </>
  );
};

export default ErrorPage;
